"""
services/gemini_prompt.py

Purpose:
This file prepares the prompt that will be sent to Gemini.

It DOES NOT perform scam detection.
Gemini only explains the result already generated by the
Scanly detection pipeline (RoBERTa + Rules + URL Analysis).

Flow:
Scan Result
      ↓
build_user_prompt()
      ↓
Gemini
      ↓
Human-readable JSON explanation
"""

# System prompt sent once with every request.
# It defines Gemini's role and the expected output format.
SYSTEM_PROMPT = """
You are SCANLY AI Assistant.

You DO NOT perform scam detection.

The classification has already been completed by the Scanly detection pipeline.

Your responsibility is ONLY to explain the existing result in clear, human-readable language.

Rules you must NEVER break:

1. Never change the category.
2. Never estimate or generate another risk score.
3. Never contradict the Scanly detection result.
4. Never classify the input yourself.
5. Return ONLY valid JSON.

Return exactly this JSON structure:

{
  "summary": "",
  "why_flagged": [],
  "safety_tips": [],
  "recommended_action": ""
}

Field Rules:

summary
- Write 2–3 simple sentences.

why_flagged
- Explain every detection reason in simple language.

safety_tips
- Provide exactly 4 practical cybersecurity tips.

recommended_action
- Give one clear next step based on the category:
  Safe / Suspicious / Scam.

Keep the complete response under 250 words.

Do not return Markdown.
Do not return code fences.
Return JSON only.
"""


def build_user_prompt(scan_data: dict) -> str:
    """
    Converts the Scanly result into a prompt for Gemini.

    Supported scan types:
    - text
    - url
    - image

    Expected scan_data:
    {
        scan_type,
        category,
        score,
        reasons,
        original_input,
        ocr_text (optional)
    }
    """

    lines = [
        f"Scan Type: {scan_data.get('scan_type', 'Unknown')}",
        f"Final Category: {scan_data.get('category', 'Unknown')}",
        f"Risk Score: {scan_data.get('score', 'N/A')}",
        f"Detection Reasons: {scan_data.get('reasons') or ['None provided']}",
    ]

    # Image Scan → Include OCR extracted text
    if (
        scan_data.get("scan_type") == "image"
        and scan_data.get("ocr_text")
    ):
        lines.append(
            f"OCR Extracted Text: {scan_data['ocr_text']}"
        )

    # URL Scan → Include scanned URL
    elif (
        scan_data.get("scan_type") == "url"
        and scan_data.get("original_input")
    ):
        lines.append(
            f"Scanned URL: {scan_data['original_input']}"
        )

    # Text Scan → Include original message
    elif (
        scan_data.get("scan_type") == "text"
        and scan_data.get("original_input")
    ):
        lines.append(
            f"Original Message: {scan_data['original_input']}"
        )

    # Final instruction to Gemini
    lines.append(
        "\nExplain this result according to the rules and JSON format defined in the system prompt."
    )

    return "\n".join(lines)