"""
services/gemini_service.py

Purpose:
Communicates with Gemini 2.5 Flash to generate a human-readable
explanation for Scanly's detection result.

Responsibilities:
- Build prompt
- Call Gemini API
- Parse JSON response
- Validate response shape
- Handle failures gracefully

Gemini NEVER performs scam detection.
It only explains the result already generated by Scanly.
"""

import json
import logging
import re

from google import genai
from google.genai import types

from core.gemini_config import gemini_settings
from services.gemini_prompt import (
    SYSTEM_PROMPT,
    build_user_prompt,
)

logger = logging.getLogger("scanly.gemini")

# Create Gemini client once when the server starts.
_client = genai.Client(
    api_key=gemini_settings.GEMINI_API_KEY
)

# Returned whenever Gemini is unavailable.
FALLBACK_RESPONSE = {
    "summary": "Human-readable explanation is currently unavailable.",
    "why_flagged": [],
    "safety_tips": [
        "Do not click unknown links.",
        "Verify the sender before responding.",
        "Never share OTPs or passwords.",
        "Use the Scanly detection result to make your decision."
    ],
    "recommended_action": "Refer to the Scanly risk category and score."
}

# Used to safely extract JSON if Gemini accidentally wraps it.
_JSON_BLOCK_RE = re.compile(r"\{.*\}", re.DOTALL)


def _extract_json(raw_text: str) -> dict:
    """
    Extracts a JSON object from Gemini's response.

    Gemini is instructed to return JSON only, but this
    acts as a safety net if markdown/code fences appear.
    """

    cleaned = raw_text.strip()

    # Remove accidental markdown fences
    cleaned = re.sub(
        r"^```(?:json)?|```$",
        "",
        cleaned,
        flags=re.MULTILINE,
    ).strip()

    match = _JSON_BLOCK_RE.search(cleaned)

    if not match:
        raise ValueError("No JSON object found in Gemini response.")

    return json.loads(match.group(0))


def _validate_shape(data: dict) -> dict:
    """
    Ensures the response always matches the expected schema.
    Prevents malformed Gemini responses from breaking the frontend.
    """

    return {
        "summary": (
            str(data.get("summary", "")).strip()
            or FALLBACK_RESPONSE["summary"]
        ),

        "why_flagged": (
            data.get("why_flagged")
            if isinstance(data.get("why_flagged"), list)
            else []
        ),

        "safety_tips": (
            data.get("safety_tips")
            if isinstance(data.get("safety_tips"), list)
            else FALLBACK_RESPONSE["safety_tips"]
        ),

        "recommended_action": (
            str(data.get("recommended_action", "")).strip()
            or FALLBACK_RESPONSE["recommended_action"]
        ),
    }


def generate_explanation(scan_data: dict) -> dict:
    """
    Generates a human-readable explanation for a Scanly result.

    Expected scan_data:

    {
        "scan_type": "text" | "url" | "image",
        "category": "Safe" | "Suspicious" | "Scam",
        "score": 85,
        "reasons": [...],
        "original_input": "...",
        "ocr_text": "..."      # image scans only
    }

    Returns:
    {
        "summary": "...",
        "why_flagged": [...],
        "safety_tips": [...],
        "recommended_action": "..."
    }

    Never raises exceptions.
    If Gemini fails, returns FALLBACK_RESPONSE.
    """

    try:

        # Build prompt from Scanly's detection result.
        user_prompt = build_user_prompt(scan_data)

        # Call Gemini
        response = _client.models.generate_content(
            model=gemini_settings.GEMINI_MODEL,

            contents=user_prompt,

            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_PROMPT,
                temperature=0.2,
                max_output_tokens=gemini_settings.GEMINI_MAX_OUTPUT_TOKENS,
                response_mime_type="application/json",
            ),
        )

        if not response.text:
            raise ValueError("Empty response received from Gemini.")

        parsed = _extract_json(response.text)

        return _validate_shape(parsed)

    except Exception as exc:
        logger.warning(
            "Gemini explanation failed. Using fallback. Error: %s",
            exc,
        )

        return dict(FALLBACK_RESPONSE)