"""
services/gemini_prompt.py

Purpose:
This file prepares the prompt that will be sent to Gemini.

It DOES NOT perform scam detection.
Gemini only explains the result already generated by the
Scanly detection pipeline (RoBERTa + Rules + URL Analysis).

Flow:
Scan Result
↓
build_user_prompt()
↓
Gemini
↓
Human-readable JSON explanation
"""


# System prompt sent with every Gemini request.
# Defines Gemini's role and expected JSON output.

SYSTEM_PROMPT = """
You are SCANLY AI Assistant.

You DO NOT perform scam detection.

The classification has already been completed by the Scanly detection pipeline.

Your responsibility is ONLY to explain the existing Scanly result in clear,
human-readable language.

Rules you must NEVER break:

1. Never change the category.
2. Never generate or modify the risk score.
3. Never contradict the Scanly detection result.
4. Never classify the input yourself.
5. Return ONLY valid JSON.

Return exactly this JSON structure:

{
  "summary": "",
  "why_flagged": [],
  "safety_tips": [],
  "recommended_action": ""
}

Field Rules:

summary:
- Write 2-3 simple sentences explaining the result.

why_flagged:
- Explain every detection reason provided by Scanly.
- Do not add new detection reasons.

safety_tips:
- Provide exactly 4 practical cybersecurity tips.

recommended_action:
- Give one clear next step based on the given category:
  Safe / Suspicious / Scam.

Response Rules:

- Keep the complete response under 250 words.
- The response must start with { and end with }.
- Do not return Markdown.
- Do not return code fences.
- Do not add explanations before or after JSON.
- Return JSON only.
"""


def build_user_prompt(scan_data: dict) -> str:
    """
    Converts the Scanly result into a prompt for Gemini.

    Supported scan types:
    - text
    - url
    - image

    Expected scan_data:

    {
        scan_type,
        category,
        score,
        reasons,
        original_input,
        ocr_text (optional)
    }
    """

    lines = [
        f"Scan Type: {scan_data.get('scan_type', 'Unknown')}",
        f"Final Category: {scan_data.get('category', 'Unknown')}",
        f"Risk Score: {scan_data.get('score', 'N/A')}",
        f"Detection Reasons: {scan_data.get('reasons') or ['None provided']}",
    ]


    # Image scan -> Include OCR extracted text
    if (
        scan_data.get("scan_type") == "image"
        and scan_data.get("ocr_text")
    ):
        lines.append(
            f"OCR Extracted Text: {scan_data['ocr_text']}"
        )


    # URL scan -> Include scanned URL
    elif (
        scan_data.get("scan_type") == "url"
        and scan_data.get("original_input")
    ):
        lines.append(
            f"Scanned URL: {scan_data['original_input']}"
        )


    # Text scan -> Include original message
    elif (
        scan_data.get("scan_type") == "text"
        and scan_data.get("original_input")
    ):
        lines.append(
            f"Original Message: {scan_data['original_input']}"
        )


    # Final instruction
    lines.append(
        "\nExplain this Scanly result using the required JSON format only."
    )

    return "\n".join(lines)