"""
===========================================================
SCANLY — Scan Routes
===========================================================

Purpose
-------
This file contains all scanning-related API endpoints.

Endpoints
---------
POST /scan/text
    • Scan plain text for scam indicators.
    • Pipeline:
      RoBERTa → Rule Engine → URL Checker → Final Score
      → Gemini Explanation

POST /scan/image
    • Scan screenshots/images.
    • Pipeline:
      OCR → RoBERTa → Rule Engine → URL Checker → Final Score
      → Gemini Explanation

POST /scan/url
    • Analyse a single URL.
    • Uses rule-based URL analysis only (no ML model).
    • → Gemini Explanation

Important
---------
Scanly's existing ML/rule-based pipeline remains the
source of truth for scam detection.

Gemini NEVER performs scam detection.
Gemini only explains the result already generated by Scanly.
If Gemini fails or times out, a fallback explanation is used —
the scan result itself is never blocked or changed by Gemini.

NOTE on response models (see models.py):
- `explanation` is a plain str — the existing rule/ML-generated
  explanation your scorer already produces. This is left as-is.
- `gemini` is a separate Optional[GeminiExplanation] field — this
  is where Gemini's structured output goes. The two are NOT the
  same field; do not overwrite `explanation` with Gemini's dict.
"""

import asyncio
from datetime import datetime, timezone

from fastapi import APIRouter, Request, UploadFile, File
from slowapi import Limiter
from slowapi.util import get_remote_address

from models import (
    ScanRequest,
    ScanResponse,
    ImageScanResponse,
    URLScanRequest,
    URLScanResponse,
)

from scorer import scan as run_scan
from services.image_scanner import scan_image as _image_service
from services.url_scanner import scan_url_only
from services import gemini_service

from db import scans_collection

from core.logging import get_logger
from core.exceptions import ModelNotLoadedError
from core.gemini_config import gemini_settings


# --------------------------------------------------------
# Router
# --------------------------------------------------------

router = APIRouter(
    prefix="/scan",
    tags=["Scanning"],
)

limiter = Limiter(
    key_func=get_remote_address,
)

logger = get_logger(__name__)


# --------------------------------------------------------
# Helper: Gemini Explanation
# --------------------------------------------------------

async def _get_explanation_safely(
    scan_data: dict,
) -> dict:
    """
    Generate Gemini explanation safely.

    Gemini runs in a worker thread so that the synchronous
    Gemini SDK call does not block the FastAPI event loop.

    A hard timeout ensures Gemini can never delay or break
    the actual Scanly detection result.

    If Gemini fails, errors, or times out, gemini_service's
    own FALLBACK_RESPONSE is returned instead.
    """

    try:

        return await asyncio.wait_for(
            asyncio.to_thread(
                gemini_service.generate_explanation,
                scan_data,
            ),
            timeout=gemini_settings.GEMINI_TIMEOUT_SECONDS,
        )

    except asyncio.TimeoutError:

        logger.warning(
            "Gemini explanation timed out"
        )

        return dict(
            gemini_service.FALLBACK_RESPONSE
        )

    except Exception as e:

        logger.warning(
            f"Gemini explanation errored: {e}"
        )

        return dict(
            gemini_service.FALLBACK_RESPONSE
        )


# --------------------------------------------------------
# Helper: Save Scan History
# --------------------------------------------------------

def _save_to_db(
    input_text: str,
    result: dict,
    scan_type: str = "text",
):
    """
    Save completed scan into MongoDB.

    Any database failure is logged but does NOT
    stop the API response.
    """

    try:

        doc = {
            "input_text": input_text,
            "final_score": result.get("final_score", 0),
            "category": result.get("category", "Unknown"),
            "confidence": result.get("confidence", 0.0),
            "ml_score": result.get("ml_score", 0),
            "rule_score": result.get("rule_score", 0),
            "url_score": result.get("url_score", 0),
            "matched_keywords": result.get(
                "matched_keywords",
                [],
            ),
            "flagged_urls": result.get(
                "flagged_urls",
                [],
            ),
            "explanation": result.get(
                "explanation",
                "",
            ),
            "gemini": result.get(
                "gemini",
                {},
            ),
            "model_version": result.get(
                "model_version",
                "roberta-base-finetuned-v1",
            ),
            "scan_type": scan_type,
            "timestamp": datetime.now(
                timezone.utc
            ).isoformat(),
        }

        scans_collection.insert_one(doc)

        logger.info(
            f"Saved {scan_type} scan "
            f"to MongoDB "
            f"(score={result.get('final_score')})"
        )

    except Exception as e:

        logger.warning(
            f"Failed to save scan history: {e}"
        )


# --------------------------------------------------------
# POST /scan/text
# --------------------------------------------------------

@router.post(
    "/text",
    response_model=ScanResponse,
)
@limiter.limit("10/minute")
async def scan_text(
    request: Request,
    body: ScanRequest,
):
    """
    Scan a text message.

    Pipeline:
    RoBERTa
        ↓
    Rule Engine
        ↓
    URL Checker
        ↓
    Final Weighted Score
        ↓
    Gemini Explanation
    """

    logger.info(
        f"Text scan request "
        f"({len(body.text)} characters)"
    )

    text = body.text

    if body.url:
        text += " " + body.url

    try:

        result = run_scan(text)

    except Exception as e:

        logger.error(
            f"Scoring pipeline failed: {e}"
        )

        raise ModelNotLoadedError()

    # ----------------------------------------------------
    # Gemini explanation (explanation-only, never detection)
    # `result["explanation"]` (str) is untouched — Gemini's
    # structured output goes into a separate `gemini` field.
    # ----------------------------------------------------

    scan_data = {
        "scan_type": "text",
        "category": result["category"],
        "score": result["final_score"],
        "reasons": result.get(
            "matched_keywords",
            [],
        ),
        "original_input": body.text,
    }

    gemini_explanation = await _get_explanation_safely(
        scan_data
    )

    result["gemini"] = gemini_explanation

    _save_to_db(
        body.text,
        result,
        scan_type="text",
    )

    return ScanResponse(
        status="success",
        input_text=body.text,
        final_score=result["final_score"],
        category=result["category"],

        # New fields
        confidence=result.get("confidence"),
        model_version=result.get("model_version"),
        processing_time_ms=result.get("processing_time_ms"),

        # Existing fields
        ml_score=result["ml_score"],
        rule_score=result["rule_score"],
        url_score=result["url_score"],
        matched_keywords=result["matched_keywords"],
        explanation=result.get("explanation", ""),

        # Gemini explanation
        gemini=gemini_explanation,
    )


# --------------------------------------------------------
# POST /scan/image
# --------------------------------------------------------

@router.post(
    "/image",
    response_model=ImageScanResponse,
)
@limiter.limit("5/minute")
async def scan_image(
    request: Request,
    file: UploadFile = File(...),
):
    """
    Scan an uploaded screenshot.

    Pipeline:
    OCR
        ↓
    RoBERTa
        ↓
    Rule Engine
        ↓
    URL Checker
        ↓
    Final Score
        ↓
    Gemini Explanation
    """

    logger.info(
        f"Image scan request: "
        f"{file.filename} "
        f"({file.content_type})"
    )

    result = await _image_service(file)

    # ----------------------------------------------------
    # Gemini explanation (explanation-only, never detection)
    # `result["explanation"]` (str, from the scorer) is left
    # untouched — Gemini's output goes into `result["gemini"]`.
    # ----------------------------------------------------

    ocr_text = result.get("extracted_text", "")

    scan_data = {
        "scan_type": "image",
        "category": result.get("category", "Unknown"),
        "score": result.get("final_score", 0),
        "reasons": result.get(
            "matched_keywords",
            [],
        ),
        "original_input": ocr_text,
        "ocr_text": ocr_text,
    }

    gemini_explanation = await _get_explanation_safely(
        scan_data
    )

    result["gemini"] = gemini_explanation

    _save_to_db(
        ocr_text,
        result,
        scan_type="image",
    )

    return result


# --------------------------------------------------------
# POST /scan/url
# --------------------------------------------------------

@router.post(
    "/url",
    response_model=URLScanResponse,
)
@limiter.limit("20/minute")
async def scan_url(
    request: Request,
    body: URLScanRequest,
):
    """
    Analyse a single URL.

    This endpoint performs only URL analysis.
    No ML model is used.

    Pipeline:
    URL Rule Engine
        ↓
    Final URL Score
        ↓
    Gemini Explanation
    """

    logger.info(
        f"URL scan request: {body.url[:60]}"
    )

    result = scan_url_only(body.url)

    # ----------------------------------------------------
    # Gemini explanation (explanation-only, never detection)
    # `result["explanation"]` (str) is untouched — Gemini's
    # structured output goes into a separate `gemini` field.
    # ----------------------------------------------------

    scan_data = {
        "scan_type": "url",
        "category": result.get("category", "Unknown"),
        "score": result.get("final_score", 0),
        "reasons": result.get("reasons", []),
        "original_input": body.url,
    }

    gemini_explanation = await _get_explanation_safely(
        scan_data
    )

    result["gemini"] = gemini_explanation

    _save_to_db(
        body.url,
        result,
        scan_type="url",
    )

    return URLScanResponse(**result)